<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    function word(){
        $groups=[
            [
                'name'=>'ก'
            ],
            [
                'name'=>'ข'
            ],
            [
                'name'=>'ค'
            ],
            [
                'name'=>'ง'
            ],
            [
                'name'=>'จ'
            ],
            [
                'name'=>'ฉ'
            ],
            [
                'name'=>'ช'
            ],
            [
                'name'=>'ซ'
            ],
            [
                'name'=>'ฌ'
            ],
            [
                'name'=>'ญ'
            ],
            [
                'name'=>'ฎ'
            ],
            [
                'name'=>'ฏ'
            ],
            [
                'name'=>'ฐ'
            ],
            [
                'name'=>'ฑ'
            ],
            [
                'name'=>'ฒ'
            ],
            [
                'name'=>'ณ'
            ],
            [
                'name'=>'ด'
            ],
            [
                'name'=>'ต'
            ],
            [
                'name'=>'ถ'
            ],
            [
                'name'=>'ท'
            ],
            [
                'name'=>'ธ'
            ],
            [
                'name'=>'น'
            ],
            [
                'name'=>'บ'
            ],
            [
                'name'=>'ป'
            ],
            [
                'name'=>'ผ'
            ],
            [
                'name'=>'ฝ'
            ],
            [
                'name'=>'พ'
            ],
            [
                'name'=>'ฟ'
            ],
            [
                'name'=>'ภ'
            ],
            [
                'name'=>'ม'
            ],
            [
                'name'=>'ย'
            ],
            [
                'name'=>'ร'
            ],
            [
                'name'=>'ล'
            ],
            [
                'name'=>'ว'
            ],
            [
                'name'=>'ศ'
            ],
            [
                'name'=>'ษ'
            ],
            [
                'name'=>'ส'
            ],
            [
                'name'=>'ห'
            ],
            [
                'name'=>'ฬ'
            ],
            [
                'name'=>'อ'
            ],
            [
                'name'=>'ฮ'
            ],
        ];
        return view('users.consonant',compact('groups'));
    }
}
